# Generated by Django 5.0.7 on 2024-10-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texnomart_uz', '0005_alter_comment_user_alter_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributekey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attribute_key/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attribute_value/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_attribute/%Y/%m/%d/'),
        ),
    ]
